server:
  port: 8002

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8002
    prefer-ip-address: true

#一般这两个必须有
spring:
  application:
    name: order-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.43.220:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: bsnlove
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.trall.springCloud.entities
mapper:
  identity: MYSQL
logging:
  level:
    root: info
